spring:
  datasource:
    url: jdbc:postgresql://ep-bold-snow-a1ae7w67-pooler.ap-southeast-1.aws.neon.tech/sudoku?sslmode=require
    username: neondb_owner
    password: npg_3J4fYSghRoHt
    driver-class-name: org.postgresql.Driver


mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: io.github.perniteo.sudoku.dto
  configuration:
    map-underscore-to-camel-case: true